package org.example;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 * Represents the start window for the exam session, displaying an exam calendar and a success button.
 * This JFrame shows the user the schedule of exams and allows them to proceed.
 */
public class ExamSessionWindow extends JFrame {
    private ExamCalendar calendarPanel;
    private JButton success;

    /**
     * Constructs a new {@code ExamSessionWindow}.
     * Initializes the frame's title, size, default close operation, layout, and adds the exam schedule label,
     * the calendar panel, and a "Успіху на сесії!" (Good luck with the session!) button.
     * The button closes the window when clicked.
     */
    public ExamSessionWindow() {
        setTitle("Рівень 3: Сесія"); // Sets the title of the window
        setSize(800, 600); // Sets the preferred size of the window
        setDefaultCloseOperation(DISPOSE_ON_CLOSE); // Specifies that the window should be disposed when closed
        setLocationRelativeTo(null); // Centers the window on the screen
        setLayout(new BorderLayout()); // Sets the layout manager for the frame to BorderLayout

        // Label for the exam schedule title
        JLabel schedule = new JLabel("Сесія: Розклад іспитів", SwingConstants.CENTER);
        schedule.setFont(new Font("Verdana", Font.BOLD, 24)); // Sets the font for the label
        schedule.setBorder(BorderFactory.createEmptyBorder(20, 0, 10, 0)); // Adds padding around the label
        add(schedule, BorderLayout.NORTH); // Adds the label to the top (NORTH) of the frame

        // Calendar panel to display exam dates
        calendarPanel = new ExamCalendar();
        add(calendarPanel, BorderLayout.CENTER); // Adds the calendar panel to the center of the frame

        // "Success" button for the session
        success = new JButton("Успіху на сесії!");
        success.setFont(new Font("Verdana", Font.BOLD, 16)); // Sets the font for the button
        success.setBackground(new Color(77, 123, 10)); // Sets the background color of the button (greenish)
        success.setForeground(Color.WHITE); // Sets the text color of the button to white
        success.setFocusPainted(false); // Removes the focus border around the button

        // ActionListener for the success button
        success.addActionListener(new ActionListener() {
            /**
             * Invoked when an action occurs (button is clicked).
             * Disposes of the current window.
             *
             * @param e The ActionEvent generated by the button click.
             */
            @Override
            public void actionPerformed(ActionEvent e) {
                dispose(); // Closes the window
            }});

        // Panel to hold the success button
        JPanel bottomPanel = new JPanel();
        bottomPanel.add(success); // Adds the button to the panel
        add(bottomPanel, BorderLayout.SOUTH); // Adds the panel to the bottom (SOUTH) of the frame
    }
}